[CmdletBinding()] param([Parameter(Mandatory)][string]$MavenVersion,[string]$SourceUrl,[switch]$SkipDownload)
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; Import-Module "$PSScriptRoot/MavenInstaller.Common.psm1" -Force
$root=Get-RepositoryRoot;$download=Join-Path $root 'artifacts/downloads';$payload=Join-Path $root 'artifacts/payload';$out=Join-Path $root 'artifacts'; New-Item $out -ItemType Directory -Force|Out-Null
$info=Get-MavenReleaseInfo $MavenVersion $SourceUrl;$zip=Join-Path $download $info.ArchiveName;$sum="$zip.sha512"
if(!$SkipDownload -or !(Test-Path $zip)){& "$PSScriptRoot/Download-Maven.ps1" -MavenVersion $MavenVersion -SourceUrl $SourceUrl -OutputDirectory $download|Out-Null}; & "$PSScriptRoot/Verify-Maven.ps1" -ArchivePath $zip -ChecksumPath $sum|Out-Null
$p=& "$PSScriptRoot/Prepare-Payload.ps1" -ArchivePath $zip -MavenVersion $MavenVersion -OutputDirectory $payload|ConvertFrom-Json
$cfg=Get-RepositoryConfig;$msi=Join-Path $out "maven-community-$MavenVersion-x64.msi";$wix=Get-Command wix -ErrorAction Stop
& $wix.Path build -acceptEula wix7 -ext WixToolset.Util.wixext -bindpath "MavenPayload=$($p.PayloadRoot)" -d "MavenVersion=$MavenVersion" -d "MsiVersion=$(Get-MsiVersion $MavenVersion)" -d "UpgradeCode=$(Get-UpgradeCode $MavenVersion)" -d "RepositoryUrl=$($cfg.RepositoryUrl)" -arch x64 -out $msi (Join-Path $root 'installer/Product.wxs') (Join-Path $root 'installer/Package.wxs')
if($LASTEXITCODE){throw 'WiX build failed.'}; $meta=[ordered]@{MavenVersion=$MavenVersion;Scope='Dual';SourceUrl=$info.SourceUrl;ArchiveSha512=(Get-FileHash $zip -Algorithm SHA512).Hash;MsiPath=$msi;MsiSha256=(Get-FileHash $msi -Algorithm SHA256).Hash;MsiSha512=(Get-FileHash $msi -Algorithm SHA512).Hash;BuiltAt=(Get-Date).ToUniversalTime().ToString('o')};$meta|ConvertTo-Json|Set-Content (Join-Path $out 'release-metadata.json');$meta|ConvertTo-Json
