name: build
on: [pull_request, push, workflow_dispatch]
permissions: { contents: read }
jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with: { dotnet-version: 8.0.x }
      - name: Install tools
        shell: pwsh
        run: |
          dotnet tool install --global wix --version 7.0.0
          & "$env:USERPROFILE\.dotnet\tools\wix.exe" eula accept wix7
          Install-Module Pester -Force -MinimumVersion 5.0.0
      - name: Test and build
        shell: pwsh
        run: |
          ./scripts/Test-Installer.ps1 -MavenVersion 3.9.16
          ./scripts/Build-Installer.ps1 -MavenVersion 3.9.16
          ./scripts/Generate-WingetManifest.ps1 -MavenVersion 3.9.16
          winget validate --manifest ./manifests/generated/Community.Maven/3.9.16
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with: { name: installer-artifacts, path: 'artifacts/,manifests/generated/' }
