name: validate winget
on: [pull_request, workflow_dispatch]
permissions: { contents: read }
jobs:
  validate:
    runs-on: windows-2025
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - shell: pwsh
        run: |
          Get-ChildItem manifests/generated -Directory -ErrorAction SilentlyContinue | ForEach-Object { winget validate --manifest $_.FullName }
